# .github/config.yaml

# Configuration for access control. This determines who can administer
# the 10x GitHub Policies application.
access_control:
  # The slug of the GitHub team whose members are authorized to manage this app.
  # Example: "octo-org/admins"
  authorized_team: "your-github-team-slug"

# A list of policies to enforce across the organization's repositories.
policies:
  - name: 'Check for AGENTS.md'
    type: 'has_agents_md'
    action: 'create-issue' # 'create-issue' or 'archive-repo'
    issue_details:
      title: 'Compliance: AGENTS.md file is missing'
      body: 'This repository is missing the AGENTS.md file in its root directory. Please add this file to comply with organization standards.'
      labels: ['policy-violation', 'documentation']

  - name: 'Check for catalog-info.yaml'
    type: 'has_catalog_info_yaml'
    action: 'create-issue'
    issue_details:
      title: 'Compliance: catalog-info.yaml is missing'
      body: 'This repository is missing the catalog-info.yaml file. This file is required for backstage.io service discovery.'
      labels: ['policy-violation', 'backstage']
