# .github/config.yaml

# Configuration for access control. Only members of this team can view the dashboard.
access_control:
  # The slug of the GitHub team authorized to access the application.
  authorized_team: "your-authorized-team-slug"

# A list of policies to enforce across all repositories in the organization.
policies:
  - type: "has_agents_md"
    action: "create_issue"
    # Additional parameters for the action can be added here if needed.
    # issueTitle: "Compliance Violation: AGENTS.md file is missing"
    # issueBody: "The AGENTS.md file was not found in this repository. Please create it to comply with organization policy."
    # issueLabels: ["compliance", "documentation"]

  - type: "has_catalog_info_yaml"
    action: "create_issue"
    # issueTitle: "Compliance Violation: catalog-info.yaml is missing"
    # issueBody: "The catalog-info.yaml file was not found. This file is required for Backstage service discovery."
    # issueLabels: ["compliance", "backstage"]

  - type: "correct_workflow_permissions"
    action: "log_only"
    # This policy will only log the violation and not take direct action.
